version: "3.9"
services:
  backend:
    build: ./backend
    image: backend:local
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
  frontend:
    build: ./frontend
    image: frontend:local
    ports:
      - "3000:3000"
    environment:
      # Service discovery by compose: "backend" resolves to container IP
      - PORT=3000
      - API_URL=http://localhost:4000
    depends_on:
      - backend


      