name: PR Cleanup
on:
  pull_request:
    types: [closed]

env:
  AZURE_RESOURCE_GROUP: aca-demo-rg

jobs:
  cleanup:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id:        ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
          subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete apps for this PR
        shell: bash
        run: |
          PR=${{ github.event.number }}
          for APP in backend-pr-$PR frontend-pr-$PR; do
            echo "Deleting $APP..."
            az containerapp delete -g $AZURE_RESOURCE_GROUP -n $APP --yes || true
          done