name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  AZURE_RESOURCE_GROUP: aca-demo-rg
  AZURE_ENVIRONMENT: aca-demo-env
  LOCATION: uksouth
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  preview:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id:        ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
          subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure Container Apps CLI extension is installed
        run: az extension add --name containerapp --upgrade

      - name: Set PR-scoped variables
        id: vars
        run: |
          echo "PR=${{ github.event.number }}" >> $GITHUB_OUTPUT
          echo "BACKEND=backend-pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          echo "FRONTEND=frontend-pr-${{ github.event.number }}" >> $GITHUB_OUTPUT

      # --- Deploy BACKEND first (public ingress) ---
      - name: Build & deploy backend
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup:              ${{ env.AZURE_RESOURCE_GROUP }}
          containerAppName:           ${{ steps.vars.outputs.BACKEND }}
          containerAppEnvironment:    ${{ env.AZURE_ENVIRONMENT }}
          acrName:                    ${{ env.ACR_NAME }}
          appSourcePath:              ./backend
          targetPort:                 4000
          ingress:                    external

      - name: Get backend FQDN
        id: get_backend
        run: |
          FQDN=$(az containerapp show -g "${{ env.AZURE_RESOURCE_GROUP }}" -n "${{ steps.vars.outputs.BACKEND }}" --query properties.configuration.ingress.fqdn -o tsv)
          echo "FQDN=$FQDN" >> $GITHUB_OUTPUT

      # --- Deploy FRONTEND (points to backend URL) ---
      - name: Build & deploy frontend
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup:              ${{ env.AZURE_RESOURCE_GROUP }}
          containerAppName:           ${{ steps.vars.outputs.FRONTEND }}
          containerAppEnvironment:    ${{ env.AZURE_ENVIRONMENT }}
          acrName:                    ${{ env.ACR_NAME }}
          appSourcePath:              ./frontend
          targetPort:                 3000
          ingress:                    external
          environmentVariables: |
            API_URL=https://${{ steps.get_backend.outputs.FQDN }}

      - name: Get frontend URL
        id: get_frontend
        run: |
          FRONTEND_FQDN=$(az containerapp show -g "${{ env.AZURE_RESOURCE_GROUP }}" -n "${{ steps.vars.outputs.FRONTEND }}" --query properties.configuration.ingress.fqdn -o tsv)
          echo "FRONTEND_URL=https://${FRONTEND_FQDN}" >> $GITHUB_OUTPUT
      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = process.env.FRONTEND_URL;
            const body = `🚀 Ephemeral preview ready: **${url}**`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          FRONTEND_URL: ${{ steps.get_frontend.outputs.FRONTEND_URL }}